---
roles:
  - src: ten7.flightdeck_base
    version: 5.1.3
  - name: ten7.mysql_backup
    src: https://github.com/ten7/mysql-backup
    version: 1.0.3
collections:
  - name: cloud.common
  - name: amazon.aws
  - name: community.general
  - name: community.mysql

